apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  labels:
    app  : my-app
    env  : test
    owner: Artem_Glazunov
spec:
  replicas: 2
  selector:
    matchLabels:
      project: ml
  template:
    metadata:
      labels:
        project: ml
    spec:
      containers:
        - name : my-app
          image: my_ml_app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-app-deployment
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70