apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  labels:
    app  : my-app
    env  : test
    owner: Artem_Glazunov
spec:
  replicas: 2
  selector:
    matchLabels:
      project: ml
  template:
    metadata:
      labels:
        project: ml
    spec:
      containers:
        - name : my-app
          image: my_ml_app
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
