apiVersion: v1
kind: Service
metadata:
  name: ml-service
spec:
  selector:
    project: ml
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 4000 #Port on LB 
      targetPort: 5000 #Port on POD